# Generated by Django 5.2.1 on 2025-06-04 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('chatbot', '0002_customerbehavior_purchasehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasehistory',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.category'),
        ),
        migrations.AddField(
            model_name='purchasehistory',
            name='last_searched',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='purchasehistory',
            name='purchase_count',
            field=models.IntegerField(default=0),
        ),
    ]
